default: &default
  redis:
    url: <%= "redis://#{ENV['REDIS_HOST'] || 'localhost'}:6379/0" %>

development:
  <<: *default

production:
  <<: *default

test:
  redis:
    url: <%= "redis://#{ENV['REDIS_HOST'] || 'localhost'}:6379/1" %>
